version: '3.9'
services:
  cancha-db:
    container_name: cancha_db
    image: postgres
    restart: always
    volumes:
      - ./cancha:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  cancha:
    driver: local
